//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkforcePlanning.Core.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorkforcePlanningEntities : DbContext
    {
        public WorkforcePlanningEntities()
            : base("name=WorkforcePlanningEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CostCentre> CostCentres { get; set; }
        public virtual DbSet<DataSourceFileConfiguration> DataSourceFileConfigurations { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeHistory> EmployeeHistories { get; set; }
        public virtual DbSet<EmploymentType> EmploymentTypes { get; set; }
        public virtual DbSet<Goa> Goas { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobFamily> JobFamilies { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LocationType> LocationTypes { get; set; }
        public virtual DbSet<PayScaleType> PayScaleTypes { get; set; }
        public virtual DbSet<PersonnelSubArea> PersonnelSubAreas { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<PositionDataSet> PositionDataSets { get; set; }
        public virtual DbSet<PositionRevision> PositionRevisions { get; set; }
        public virtual DbSet<SourceFileColumnMapping> SourceFileColumnMappings { get; set; }
        public virtual DbSet<SubGroup> SubGroups { get; set; }
        public virtual DbSet<WorkSchedule> WorkSchedules { get; set; }
        public virtual DbSet<PositionHistory> PositionHistories { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<TaskDefinition> TaskDefinitions { get; set; }
        public virtual DbSet<TaskDefinitionDetail> TaskDefinitionDetails { get; set; }
        public virtual DbSet<TaskStatu> TaskStatus { get; set; }
        public virtual DbSet<TaskType> TaskTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
