//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkforcePlanning.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Position()
        {
            this.DirectReports = new HashSet<Position>();
            this.PositionRevisions = new HashSet<PositionRevision>();
        }
    
        public string Number { get; set; }
        public int PositionDataSetId { get; set; }
        public string ManagingPositionNumber { get; set; }
        public string EmployeeNumber { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<int> JobFamilyId { get; set; }
        public Nullable<int> GoaId { get; set; }
        public Nullable<int> CostCentreId { get; set; }
        public Nullable<int> HomeCostCentreId { get; set; }
        public Nullable<int> FlowToCostCentreId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> WorkLocationId { get; set; }
        public Nullable<int> SubGroupId { get; set; }
        public Nullable<int> EmploymentTypeId { get; set; }
        public Nullable<int> PersonnelSubAreaId { get; set; }
        public Nullable<int> PayScaleTypeId { get; set; }
        public Nullable<int> WorkScheduleId { get; set; }
        public string Title { get; set; }
        public string PayScaleGroupMin { get; set; }
        public string PayScaleGroupMax { get; set; }
        public string PayScaleLevelMin { get; set; }
        public string PayScaleLevelMax { get; set; }
        public bool OvertimeExempt { get; set; }
        public bool HardToRecruit { get; set; }
        public bool DoesCountAsHeadCount { get; set; }
        public bool IsCriticalSkill { get; set; }
        public Nullable<System.DateTime> PlannedStartDate { get; set; }
        public Nullable<System.DateTime> PlannedEndDate { get; set; }
        public decimal PlanningSalary { get; set; }
        public decimal EmploymentPercentage { get; set; }
        public decimal FullTimeEquivalencyPercentage { get; set; }
        public Nullable<int> PlanningSalaryBand { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual CostCentre CostCentre { get; set; }
        public virtual CostCentre FlowToCostCentre { get; set; }
        public virtual CostCentre HomeCostCentre { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual EmploymentType EmploymentType { get; set; }
        public virtual Goa Goa { get; set; }
        public virtual Job Job { get; set; }
        public virtual JobFamily JobFamily { get; set; }
        public virtual Location Location { get; set; }
        public virtual Location WorkLocation { get; set; }
        public virtual PayScaleType PayScaleType { get; set; }
        public virtual PersonnelSubArea PersonnelSubArea { get; set; }
        public virtual PositionDataSet PositionDataSet { get; set; }
        public virtual SubGroup SubGroup { get; set; }
        public virtual WorkSchedule WorkSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Position> DirectReports { get; set; }
        public virtual Position ManagingPosition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PositionRevision> PositionRevisions { get; set; }
    }
}
