//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkforcePlanning.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PositionHistory
    {
        public int Id { get; set; }
        public int PositionDataSetId { get; set; }
        public string ManagingPositionNumber { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<int> JobFamilyId { get; set; }
        public Nullable<int> GoaId { get; set; }
        public Nullable<int> CostCentreId { get; set; }
        public Nullable<int> HomeCostCentreId { get; set; }
        public Nullable<int> FlowToCostCentreId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> WorkLocationId { get; set; }
        public Nullable<int> SubGroupId { get; set; }
        public Nullable<int> EmploymentTypeId { get; set; }
        public Nullable<int> PersonnelSubAreaId { get; set; }
        public Nullable<int> PayScaleTypeId { get; set; }
        public Nullable<int> WorkScheduleId { get; set; }
        public string EmployeeNumber { get; set; }
        public string Title { get; set; }
        public string Number { get; set; }
        public string PayScaleGroupMin { get; set; }
        public string PayScaleGroupMax { get; set; }
        public string PayScaleLevelMin { get; set; }
        public string PayScaleLevelMax { get; set; }
        public bool OvertimeExempt { get; set; }
        public bool HardToRecruit { get; set; }
        public bool DoesCountAsHeadCount { get; set; }
        public bool IsCriticalSkill { get; set; }
        public Nullable<System.DateTime> PlannedStartDate { get; set; }
        public Nullable<System.DateTime> PlannedEndDate { get; set; }
        public decimal PlanningSalary { get; set; }
        public decimal EmploymentPercentage { get; set; }
        public decimal FullTimeEquivalencyPercentage { get; set; }
        public Nullable<int> PlanningSalaryBand { get; set; }
        public string ModifiedBy { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
