//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkforcePlanning.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public int TaskDefinitionDetailId { get; set; }
        public Nullable<int> AssignedToUserId { get; set; }
        public Nullable<int> PositionRevisionId { get; set; }
        public int TaskStatusId { get; set; }
        public int Number { get; set; }
        public System.DateTime TaskStatusDate { get; set; }
        public string Comments { get; set; }
        public System.DateTime EffectiveFromDate { get; set; }
        public Nullable<System.DateTime> EffectiveToDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual PositionRevision PositionRevision { get; set; }
        public virtual TaskDefinitionDetail TaskDefinitionDetail { get; set; }
        public virtual TaskStatu TaskStatu { get; set; }
        public virtual User User { get; set; }
    }
}
